name: Integration test for wasi

on:
  pull_request:
    branches: ["main"]

jobs:
  wasi:
    strategy:
      fail-fast: false
      matrix:
        platforms:
        - wasm/wasi
        - wasm/wasi,linux/amd64
        - all,wasm/wasi
    name: wasi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
      - name: setup tinygo
        shell: bash
        env:
          TINYGO_VERSION: 0.23.0
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v"${TINYGO_VERSION}"/tinygo_${TINYGO_VERSION}_amd64.deb
          sudo dpkg -i tinygo_${TINYGO_VERSION}_amd64.deb
      - name: integration test for wasi
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update && apt-get install uuid-runtime
          docker build -f test/wasi/Dockerfile.test -t podman-with-crun .
          export KO_DOCKER_REPO=ttl.sh/$(uuidgen |tr "[:upper:]" "[:lower:]") 
          export testimg=$(go run main.go build ./test/wasi --platform=${{ matrix.platforms }})
          export output=$(docker run --privileged podman-with-crun run --platform=wasm/wasi $testimg)
          echo $output | grep "hello from wasi"